name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    uses: silverstripe/github-actions-ci-cd/.github/workflows/ci.yml@v1
    with:
      php_versions: '["8.1", "8.2"]'
      db_types: '["mysql"]'
    secrets:
      FOXY_WEBHOOK_KEY: ${{ secrets.FOXY_WEBHOOK_KEY }}
